name: Deploy ODS

on:
  workflow_dispatch:
    inputs:
      vm_name:
        description: "The name of the VM to run the command on"
        required: true
      resource_group:
        description: "The resource group of the VM"
        required: true
      target_environment:
        description: "Select the environment"
        required: true
        type: choice
        options:
          - develop
        default: staging

env:
  ARM_CLIENT_ID: ${{ vars.AZURE_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ vars.AZURE_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ vars.AZURE_TENANT_ID }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.target_environment }}
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: '{"clientId":"${{ env.ARM_CLIENT_ID }}","clientSecret":"${{ env.ARM_CLIENT_SECRET }}","subscriptionId":"${{ env.ARM_SUBSCRIPTION_ID }}","tenantId":"${{ env.ARM_TENANT_ID }}"}'

      - name: Run Deployment Commands
        run: |
          SCRIPT_CONTENT='
          Set-Location "C:\Temp\EdFi.Suite3.RestApi.Databases.Standard"
          
          Write-Host "Creating ps1 file..."
          "Import-Module .\Deployment.psm1" | Out-File -FilePath "test.ps1"
          "Initialize-DeploymentEnvironment" | Out-File -FilePath "test.ps1" -Append
          
          Write-Host "File created successfully"
          Get-Content -Path "test.ps1"'
          
          az vm run-command invoke \
            --command-id RunPowerShellScript \
            --name "${{ github.event.inputs.vm_name }}" \
            --resource-group "${{ github.event.inputs.resource_group }}" \
            --scripts "$SCRIPT_CONTENT" 

      - name: Execute PowerShell Command on Azure VM
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: 13.86.213.253
          username: exampleadmin
          password: Password1234!
          port: 22
          script: powershell.exe -Command "Start-Process -FilePath 'C:\\Temp\\EdFi.Suite3.RestApi.Databases.Standard\\test.ps1' -ArgumentList '-ExecutionPolicy Bypass' -Verb RunAs"
          timeout: 60s
          command_timeout: 20m
          debug: true