name: Deploy ODS

on:
  workflow_dispatch:
    inputs:
      vm_name:
        description: "The name of the VM to run the command on"
        required: true
      resource_group:
        description: "The resource group of the VM"
        required: true
      target_environment:
        description: "Select the environment"
        required: true
        type: choice
        options:
          - develop
        default: staging

env:
  ARM_CLIENT_ID: ${{ vars.AZURE_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ vars.AZURE_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ vars.AZURE_TENANT_ID }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.target_environment }}
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: '{"clientId":"${{ env.ARM_CLIENT_ID }}","clientSecret":"${{ env.ARM_CLIENT_SECRET }}","subscriptionId":"${{ env.ARM_SUBSCRIPTION_ID }}","tenantId":"${{ env.ARM_TENANT_ID }}"}'

      - name: Run Deployment Commands
        run: |
          az vm run-command invoke \
            --command-id RunPowerShellScript \
            --name "${{ github.event.inputs.vm_name }}" \
            --resource-group "${{ github.event.inputs.resource_group }}" \
            --scripts '
            try {
                Set-Location "C:\Temp\EdFi.Suite3.RestApi.Databases.Standard"
                
                # Update configuration to trust server certificate
                $configPath = ".\configuration.json"
                if (Test-Path $configPath) {
                    $config = Get-Content $configPath | ConvertFrom-Json
                    if ($config.connectionStrings) {
                        $config.connectionStrings | Get-Member -MemberType NoteProperty | ForEach-Object {
                            $connStr = $config.connectionStrings.($_.Name)
                            if ($connStr -notlike "*TrustServerCertificate=True*") {
                                $config.connectionStrings.($_.Name) = "$connStr;TrustServerCertificate=True"
                            }
                        }
                        $config | ConvertTo-Json -Depth 10 | Set-Content $configPath
                        Write-Host "Updated configuration.json with TrustServerCertificate=True"
                    }
                }
                
                Write-Host "Importing module..."
                Import-Module .\Deployment.psm1
                
                Write-Host "Starting deployment..."
                Initialize-DeploymentEnvironment
                
                Write-Host "Deployment completed successfully"
            }
            catch {
                Write-Error "Error occurred: $_"
                exit 1
            }' 